name: build-and-deploy-portfolio
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'content/**'
      
jobs:
  build-and-deploy-portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: cd content && npm install
      
      - name: Build astro project
        run: cd content && npm run astro build
        
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa www.rgorbach.dev >> ~/.ssh/known_hosts
          
      - name: Deploy to remote server
        run: |
          MAX_RETRIES=5
          COUNT=0
          while[[ $COUNT -lt $MAX_RETRIES ]]
            scp -r -o "BatchMode yes" ./content/dist/* ${{secrets.SSH_USER}}@www.rgorbach.dev:/var/www/html && break

            COUNT=$((COUNT+1))
            echo "ATTEMPT $COUNT FAILED RETRYING IN 10 SECONDS..."
            sleep 10
          done
          if [[ $COUNT -eq $MAX_RETRIES ]] then
            echo "Failed after $MAX_RETRIES attempts!"
            exit 1
          fi
          
