name: build-and-deploy-portfolio
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      
jobs:
  build-and-deploy-portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install
      
      - name: Build parcel project
        run: npm run build
        
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa www.rgorbach.dev >> ~/.ssh/known_hosts
          
      - name: Deploy to remote server
        run: scp -r -o "BatchMode yes" ./public/* ${{secrets.SSH_USER}}@www.rgorbach.dev:/var/www/html
